service: aws-fanout-pattern

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.13
  region: ${opt:region, 'us-east-1'}
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
        - sns:Publish
        Resource: ${file(../terraform/outputs.json):sns_topic_arn}
      - Effect: Allow
        Action:
        - dynamodb:PutItem
        Resource: ${file(../terraform/outputs.json):dynamodb_table_arn}

functions:
  publisher:
    handler: handlers.publisher.handler
    environment:
      SNS_TOPIC_ARN: ${file(../terraform/outputs.json):sns_topic_arn}
    events:
    - httpApi:
        path: /publish
        method: post

  consumer_1:
    handler: handlers.consumer.handler
    environment:
      DDB_TABLE_NAME: ${file(../terraform/outputs.json):dynamodb_table_name}
      CONSUMER_ID: consumer_1
    events:
    - sqs:
        arn: ${file(../terraform/outputs.json):queue_1_arn}

  consumer_2:
    handler: handlers.consumer.handler
    environment:
      DDB_TABLE_NAME: ${file(../terraform/outputs.json):dynamodb_table_name}
      CONSUMER_ID: consumer_2
    events:
    - sqs:
        arn: ${file(../terraform/outputs.json):queue_2_arn}

  consumer_3:
    handler: handlers.consumer.handler
    environment:
      DDB_TABLE_NAME: ${file(../terraform/outputs.json):dynamodb_table_name}
      CONSUMER_ID: consumer_3
    events:
    - sqs:
        arn: ${file(../terraform/outputs.json):queue_3_arn}

plugins:
- serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: false
    pythonBin: python3
